name: Web Playwright Tests

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: "Select test suite to run"
        required: true
        default: "Run All Available Testing"
        type: choice
        options:
          - "E2E Testing"
          - "Login Scenario"
          - "Run All Available Testing"

jobs:
  web-tests:
    runs-on: ubuntu-22.04

    env:
      HEADLESS: true   # 🔥 paksa headless di CI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium

      - name: Run pytest
        run: |
          mkdir -p reports

          if [ "${{ github.event.inputs.test_suite }}" = "E2E Testing" ]; then
            TEST_TARGET="web/tests/test_checkout_e2e.py"
          elif [ "${{ github.event.inputs.test_suite }}" = "Login Scenario" ]; then
            TEST_TARGET="web/tests/test_login_scenario.py"
          elif [ "${{ github.event.inputs.test_suite }}" = "Run All Available Testing" ]; then
            TEST_TARGET="web/tests"
          else
            echo "Invalid test suite selected"
            exit 1
          fi

          pytest -v "$TEST_TARGET" --html=reports/report.html --self-contained-html

      - name: Upload pytest html report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report-${{ github.event.inputs.test_suite }}
          path: reports/report.html
          if-no-files-found: ignore